name: prueba
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  url_launcher: ^6.1.10
  image_picker: ^1.1.2
  webview_flutter: ^4.2.3
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  shared_preferences: ^2.1.1
  crypto: ^3.0.2
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  cupertino_icons: ^1.0.5
  google_mobile_ads: 5.2.0
  in_app_purchase: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: KGRedHands
      fonts:
        - asset: assets/fonts/KGRedHands.ttf
  assets:
    - assets/logo.png
    - assets/local1.png
    - assets/local2.png
    - assets/local3.png
    - assets/default_user.png
    - assets/key.json

  uses-material-design: true
