// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1rLM1mM7KIGQakDNUC4P1yqRBO0oDtNM',
    appId: '1:513564820398:web:82ee93e668fb0d07bbfe3f',
    messagingSenderId: '513564820398',
    projectId: 'marylandbarber',
    authDomain: 'marylandbarber.firebaseapp.com',
    storageBucket: 'marylandbarber.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16G4nIXukPtlipNYJePreHekAb9oB4wA',
    appId: '1:513564820398:android:6ee486398c38d588bbfe3f',
    messagingSenderId: '513564820398',
    projectId: 'marylandbarber',
    storageBucket: 'marylandbarber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_pXMbBeKfGBf2y5MmPKsqEpiJPmx7C0',
    appId: '1:513564820398:ios:9968c4b94660721ebbfe3f',
    messagingSenderId: '513564820398',
    projectId: 'marylandbarber',
    storageBucket: 'marylandbarber.appspot.com',
    iosBundleId: 'com.marylandbarbershop.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_pXMbBeKfGBf2y5MmPKsqEpiJPmx7C0',
    appId: '1:513564820398:ios:669feb22b608fcedbbfe3f',
    messagingSenderId: '513564820398',
    projectId: 'marylandbarber',
    storageBucket: 'marylandbarber.appspot.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1rLM1mM7KIGQakDNUC4P1yqRBO0oDtNM',
    appId: '1:513564820398:web:2acd909a57dc5ea9bbfe3f',
    messagingSenderId: '513564820398',
    projectId: 'marylandbarber',
    authDomain: 'marylandbarber.firebaseapp.com',
    storageBucket: 'marylandbarber.appspot.com',
  );
}
